### ISSUE TITLE
Left-Alignment Bug

### ISSUE THREAD

**Issue by ebollens** [ucla/mwf#156]
This definition in `root/assets/css/default/basic.src.css` is incorrect:

``` css
 .menu.left > ul > li,
 .menu.detailed > ol > li {
     text-align: left;
 }
```

It should be:

``` css
 .menu.left > ul > li,
 .menu.left > ol > li,
 .menu.detailed > ul > li,
 .menu.detailed > ol > li {
     text-align: left;
 }
```
